[build]
  builder = "nixpacks"

[build.nixpacks]
  python = "3.12"

[deploy]
  startCommand = "python main.py"
  numReplicas = 1
  sleepApplication = false
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10
